//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//
package gerbera.fdsnws.datamodel;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAnyAttribute;
import jakarta.xml.bind.annotation.XmlAnyElement;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.bind.annotation.XmlType;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;
import org.w3c.dom.Element;

/**
 * A base node type for derivation from: Network, Station and Channel types.
 *
 * <p>
 * Java class for BaseNodeType complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType name="BaseNodeType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Identifier" type="{http://www.fdsn.org/xml/station/1}IdentifierType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="Comment" type="{http://www.fdsn.org/xml/station/1}CommentType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="DataAvailability" type="{http://www.fdsn.org/xml/station/1}DataAvailabilityType" minOccurs="0"/&gt;
 *         &lt;any processContents='lax' namespace='##other' maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="code" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="startDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" /&gt;
 *       &lt;attribute name="endDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" /&gt;
 *       &lt;attribute name="sourceID" type="{http://www.w3.org/2001/XMLSchema}anyURI" /&gt;
 *       &lt;attribute name="restrictedStatus" type="{http://www.fdsn.org/xml/station/1}RestrictedStatusType" /&gt;
 *       &lt;attribute name="alternateCode" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="historicalCode" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;anyAttribute processContents='lax' namespace='##other'/&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BaseNodeType", propOrder = {
	"description",
	"identifier",
	"comment",
	"dataAvailability",
	"any"
})
@XmlSeeAlso({
	NetworkType.class,
	StationType.class,
	ChannelType.class
})
public class BaseNodeType {

	@XmlElement(name = "Description")
	protected String description;
	@XmlElement(name = "Identifier")
	protected List<IdentifierType> identifier;
	@XmlElement(name = "Comment")
	protected List<CommentType> comment;
	@XmlElement(name = "DataAvailability")
	protected DataAvailabilityType dataAvailability;
	@XmlAnyElement(lax = true)
	protected List<Object> any;
	@XmlAttribute(name = "code", required = true)
	protected String code;
	@XmlAttribute(name = "startDate")
	@XmlSchemaType(name = "dateTime")
	protected XMLGregorianCalendar startDate;
	@XmlAttribute(name = "endDate")
	@XmlSchemaType(name = "dateTime")
	protected XMLGregorianCalendar endDate;
	@XmlAttribute(name = "sourceID")
	@XmlSchemaType(name = "anyURI")
	protected String sourceID;
	@XmlAttribute(name = "restrictedStatus")
	protected RestrictedStatusType restrictedStatus;
	@XmlAttribute(name = "alternateCode")
	protected String alternateCode;
	@XmlAttribute(name = "historicalCode")
	protected String historicalCode;
	@XmlAnyAttribute
	private Map<QName, String> otherAttributes = new HashMap<QName, String>();

	/**
	 * Gets the value of the description property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * Sets the value of the description property.
	 *
	 * @param value allowed object is {@link String }
	 *
	 */
	public void setDescription(String value) {
		this.description = value;
	}

	/**
	 * Gets the value of the identifier property.
	 *
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the identifier property.
	 *
	 * <p>
	 * For example, to add a new item, do as follows:
	 * <pre>
	 *    getIdentifier().add(newItem);
	 * </pre>
	 *
	 *
	 * <p>
	 * Objects of the following type(s) are allowed in the list
     * {@link IdentifierType }
	 *
	 *
	 */
	public List<IdentifierType> getIdentifier() {
		if (identifier == null) {
			identifier = new ArrayList<IdentifierType>();
		}
		return this.identifier;
	}

	/**
	 * Gets the value of the comment property.
	 *
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the comment property.
	 *
	 * <p>
	 * For example, to add a new item, do as follows:
	 * <pre>
	 *    getComment().add(newItem);
	 * </pre>
	 *
	 *
	 * <p>
	 * Objects of the following type(s) are allowed in the list
     * {@link CommentType }
	 *
	 *
	 */
	public List<CommentType> getComment() {
		if (comment == null) {
			comment = new ArrayList<CommentType>();
		}
		return this.comment;
	}

	/**
	 * Gets the value of the dataAvailability property.
	 *
	 * @return possible object is {@link DataAvailabilityType }
	 *
	 */
	public DataAvailabilityType getDataAvailability() {
		return dataAvailability;
	}

	/**
	 * Sets the value of the dataAvailability property.
	 *
	 * @param value allowed object is {@link DataAvailabilityType }
	 *
	 */
	public void setDataAvailability(DataAvailabilityType value) {
		this.dataAvailability = value;
	}

	/**
	 * Gets the value of the any property.
	 *
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the any property.
	 *
	 * <p>
	 * For example, to add a new item, do as follows:
	 * <pre>
	 *    getAny().add(newItem);
	 * </pre>
	 *
	 *
	 * <p>
	 * Objects of the following type(s) are allowed in the list null	null	null	 {@link Element }
     * {@link Object }
	 *
	 *
	 */
	public List<Object> getAny() {
		if (any == null) {
			any = new ArrayList<Object>();
		}
		return this.any;
	}

	/**
	 * Gets the value of the code property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getCode() {
		return code;
	}

	/**
	 * Sets the value of the code property.
	 *
	 * @param value allowed object is {@link String }
	 *
	 */
	public void setCode(String value) {
		this.code = value;
	}

	/**
	 * Gets the value of the startDate property.
	 *
	 * @return possible object is {@link XMLGregorianCalendar }
	 *
	 */
	public XMLGregorianCalendar getStartDate() {
		return startDate;
	}

	/**
	 * Sets the value of the startDate property.
	 *
	 * @param value allowed object is {@link XMLGregorianCalendar }
	 *
	 */
	public void setStartDate(XMLGregorianCalendar value) {
		this.startDate = value;
	}

	/**
	 * Gets the value of the endDate property.
	 *
	 * @return possible object is {@link XMLGregorianCalendar }
	 *
	 */
	public XMLGregorianCalendar getEndDate() {
		return endDate;
	}

	/**
	 * Sets the value of the endDate property.
	 *
	 * @param value allowed object is {@link XMLGregorianCalendar }
	 *
	 */
	public void setEndDate(XMLGregorianCalendar value) {
		this.endDate = value;
	}

	/**
	 * Gets the value of the sourceID property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getSourceID() {
		return sourceID;
	}

	/**
	 * Sets the value of the sourceID property.
	 *
	 * @param value allowed object is {@link String }
	 *
	 */
	public void setSourceID(String value) {
		this.sourceID = value;
	}

	/**
	 * Gets the value of the restrictedStatus property.
	 *
	 * @return possible object is {@link RestrictedStatusType }
	 *
	 */
	public RestrictedStatusType getRestrictedStatus() {
		return restrictedStatus;
	}

	/**
	 * Sets the value of the restrictedStatus property.
	 *
	 * @param value allowed object is {@link RestrictedStatusType }
	 *
	 */
	public void setRestrictedStatus(RestrictedStatusType value) {
		this.restrictedStatus = value;
	}

	/**
	 * Gets the value of the alternateCode property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getAlternateCode() {
		return alternateCode;
	}

	/**
	 * Sets the value of the alternateCode property.
	 *
	 * @param value allowed object is {@link String }
	 *
	 */
	public void setAlternateCode(String value) {
		this.alternateCode = value;
	}

	/**
	 * Gets the value of the historicalCode property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getHistoricalCode() {
		return historicalCode;
	}

	/**
	 * Sets the value of the historicalCode property.
	 *
	 * @param value allowed object is {@link String }
	 *
	 */
	public void setHistoricalCode(String value) {
		this.historicalCode = value;
	}

	/**
	 * Gets a map that contains attributes that aren't bound to any typed
	 * property on this class.
	 *
	 * <p>
	 * the map is keyed by the name of the attribute and the value is the string
	 * value of the attribute.
	 *
	 * the map returned by this method is live, and you can add new attribute by
	 * updating the map directly. Because of this design, there's no setter.
	 *
	 *
	 * @return always non-null
	 */
	public Map<QName, String> getOtherAttributes() {
		return otherAttributes;
	}

}
