//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema.
//
package gerbera.fdsnws.datamodel;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

import java.util.ArrayList;
import java.util.List;

/**
 * Equivalent to SEED blockette 52 and parent element for the related the
 * response blockettes.
 *
 * <p>
 * Java class for ChannelType complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType name="ChannelType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.fdsn.org/xml/station/1}BaseNodeType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ExternalReference" type="{http://www.fdsn.org/xml/station/1}ExternalReferenceType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="Latitude" type="{http://www.fdsn.org/xml/station/1}LatitudeType"/&gt;
 *         &lt;element name="Longitude" type="{http://www.fdsn.org/xml/station/1}LongitudeType"/&gt;
 *         &lt;element name="Elevation" type="{http://www.fdsn.org/xml/station/1}DistanceType"/&gt;
 *         &lt;element name="Depth" type="{http://www.fdsn.org/xml/station/1}DistanceType"/&gt;
 *         &lt;element name="Azimuth" type="{http://www.fdsn.org/xml/station/1}AzimuthType" minOccurs="0"/&gt;
 *         &lt;element name="Dip" type="{http://www.fdsn.org/xml/station/1}DipType" minOccurs="0"/&gt;
 *         &lt;element name="WaterLevel" type="{http://www.fdsn.org/xml/station/1}FloatType" minOccurs="0"/&gt;
 *         &lt;element name="Type" maxOccurs="unbounded" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN"&gt;
 *               &lt;enumeration value="TRIGGERED"/&gt;
 *               &lt;enumeration value="CONTINUOUS"/&gt;
 *               &lt;enumeration value="HEALTH"/&gt;
 *               &lt;enumeration value="GEOPHYSICAL"/&gt;
 *               &lt;enumeration value="WEATHER"/&gt;
 *               &lt;enumeration value="FLAG"/&gt;
 *               &lt;enumeration value="SYNTHESIZED"/&gt;
 *               &lt;enumeration value="INPUT"/&gt;
 *               &lt;enumeration value="EXPERIMENTAL"/&gt;
 *               &lt;enumeration value="MAINTENANCE"/&gt;
 *               &lt;enumeration value="BEAM"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;group ref="{http://www.fdsn.org/xml/station/1}SampleRateGroup" minOccurs="0"/&gt;
 *         &lt;element name="ClockDrift" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;simpleContent&gt;
 *               &lt;restriction base="&lt;http://www.fdsn.org/xml/station/1&gt;FloatType"&gt;
 *                 &lt;attribute name="unit" type="{http://www.w3.org/2001/XMLSchema}string" fixed="SECONDS/SAMPLE" /&gt;
 *               &lt;/restriction&gt;
 *             &lt;/simpleContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="CalibrationUnits" type="{http://www.fdsn.org/xml/station/1}UnitsType" minOccurs="0"/&gt;
 *         &lt;element name="Sensor" type="{http://www.fdsn.org/xml/station/1}EquipmentType" minOccurs="0"/&gt;
 *         &lt;element name="PreAmplifier" type="{http://www.fdsn.org/xml/station/1}EquipmentType" minOccurs="0"/&gt;
 *         &lt;element name="DataLogger" type="{http://www.fdsn.org/xml/station/1}EquipmentType" minOccurs="0"/&gt;
 *         &lt;element name="Equipment" type="{http://www.fdsn.org/xml/station/1}EquipmentType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="Response" type="{http://www.fdsn.org/xml/station/1}ResponseType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="locationCode" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;anyAttribute processContents='lax' namespace='##other'/&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ChannelType", propOrder = {
	"externalReference",
	"latitude",
	"longitude",
	"elevation",
	"depth",
	"azimuth",
	"dip",
	"waterLevel",
	"type",
	"sampleRate",
	"sampleRateRatio",
	"clockDrift",
	"calibrationUnits",
	"sensor",
	"preAmplifier",
	"dataLogger",
	"equipment",
	"response"
})
public class ChannelType
		extends BaseNodeType {

	@XmlElement(name = "ExternalReference")
	protected List<ExternalReferenceType> externalReference;
	@XmlElement(name = "Latitude", required = true)
	protected LatitudeType latitude;
	@XmlElement(name = "Longitude", required = true)
	protected LongitudeType longitude;
	@XmlElement(name = "Elevation", required = true)
	protected DistanceType elevation;
	@XmlElement(name = "Depth", required = true)
	protected DistanceType depth;
	@XmlElement(name = "Azimuth")
	protected AzimuthType azimuth;
	@XmlElement(name = "Dip")
	protected DipType dip;
	@XmlElement(name = "WaterLevel")
	protected FloatType waterLevel;
	@XmlElement(name = "Type")
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	protected List<String> type;
	@XmlElement(name = "SampleRate")
	protected SampleRateType sampleRate;
	@XmlElement(name = "SampleRateRatio")
	protected SampleRateRatioType sampleRateRatio;
	@XmlElement(name = "ClockDrift")
	protected ChannelType.ClockDrift clockDrift;
	@XmlElement(name = "CalibrationUnits")
	protected UnitsType calibrationUnits;
	@XmlElement(name = "Sensor")
	protected EquipmentType sensor;
	@XmlElement(name = "PreAmplifier")
	protected EquipmentType preAmplifier;
	@XmlElement(name = "DataLogger")
	protected EquipmentType dataLogger;
	@XmlElement(name = "Equipment")
	protected List<EquipmentType> equipment;
	@XmlElement(name = "Response")
	protected ResponseType response;
	@XmlAttribute(name = "locationCode", required = true)
	protected String locationCode;

	/**
	 * Gets the value of the externalReference property.
	 *
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the externalReference property.
	 *
	 * <p>
	 * For example, to add a new item, do as follows:
	 * <pre>
	 *    getExternalReference().add(newItem);
	 * </pre>
	 *
	 *
	 * <p>
	 * Objects of the following type(s) are allowed in the list
     * {@link ExternalReferenceType }
	 *
	 *
	 */
	public List<ExternalReferenceType> getExternalReference() {
		if (externalReference == null) {
			externalReference = new ArrayList<ExternalReferenceType>();
		}
		return this.externalReference;
	}

	/**
	 * Gets the value of the latitude property.
	 *
	 * @return possible object is {@link LatitudeType }
	 *
	 */
	public LatitudeType getLatitude() {
		return latitude;
	}

	/**
	 * Sets the value of the latitude property.
	 *
	 * @param value allowed object is {@link LatitudeType }
	 *
	 */
	public void setLatitude(LatitudeType value) {
		this.latitude = value;
	}

	/**
	 * Gets the value of the longitude property.
	 *
	 * @return possible object is {@link LongitudeType }
	 *
	 */
	public LongitudeType getLongitude() {
		return longitude;
	}

	/**
	 * Sets the value of the longitude property.
	 *
	 * @param value allowed object is {@link LongitudeType }
	 *
	 */
	public void setLongitude(LongitudeType value) {
		this.longitude = value;
	}

	/**
	 * Gets the value of the elevation property.
	 *
	 * @return possible object is {@link DistanceType }
	 *
	 */
	public DistanceType getElevation() {
		return elevation;
	}

	/**
	 * Sets the value of the elevation property.
	 *
	 * @param value allowed object is {@link DistanceType }
	 *
	 */
	public void setElevation(DistanceType value) {
		this.elevation = value;
	}

	/**
	 * Gets the value of the depth property.
	 *
	 * @return possible object is {@link DistanceType }
	 *
	 */
	public DistanceType getDepth() {
		return depth;
	}

	/**
	 * Sets the value of the depth property.
	 *
	 * @param value allowed object is {@link DistanceType }
	 *
	 */
	public void setDepth(DistanceType value) {
		this.depth = value;
	}

	/**
	 * Gets the value of the azimuth property.
	 *
	 * @return possible object is {@link AzimuthType }
	 *
	 */
	public AzimuthType getAzimuth() {
		return azimuth;
	}

	/**
	 * Sets the value of the azimuth property.
	 *
	 * @param value allowed object is {@link AzimuthType }
	 *
	 */
	public void setAzimuth(AzimuthType value) {
		this.azimuth = value;
	}

	/**
	 * Gets the value of the dip property.
	 *
	 * @return possible object is {@link DipType }
	 *
	 */
	public DipType getDip() {
		return dip;
	}

	/**
	 * Sets the value of the dip property.
	 *
	 * @param value allowed object is {@link DipType }
	 *
	 */
	public void setDip(DipType value) {
		this.dip = value;
	}

	/**
	 * Gets the value of the waterLevel property.
	 *
	 * @return possible object is {@link FloatType }
	 *
	 */
	public FloatType getWaterLevel() {
		return waterLevel;
	}

	/**
	 * Sets the value of the waterLevel property.
	 *
	 * @param value allowed object is {@link FloatType }
	 *
	 */
	public void setWaterLevel(FloatType value) {
		this.waterLevel = value;
	}

	/**
	 * Gets the value of the type property.
	 *
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the type property.
	 *
	 * <p>
	 * For example, to add a new item, do as follows:
	 * <pre>
	 *    getType().add(newItem);
	 * </pre>
	 *
	 *
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link String }
	 *
	 *
	 */
	public List<String> getType() {
		if (type == null) {
			type = new ArrayList<String>();
		}
		return this.type;
	}

	/**
	 * Gets the value of the sampleRate property.
	 *
	 * @return possible object is {@link SampleRateType }
	 *
	 */
	public SampleRateType getSampleRate() {
		return sampleRate;
	}

	/**
	 * Sets the value of the sampleRate property.
	 *
	 * @param value allowed object is {@link SampleRateType }
	 *
	 */
	public void setSampleRate(SampleRateType value) {
		this.sampleRate = value;
	}

	/**
	 * Gets the value of the sampleRateRatio property.
	 *
	 * @return possible object is {@link SampleRateRatioType }
	 *
	 */
	public SampleRateRatioType getSampleRateRatio() {
		return sampleRateRatio;
	}

	/**
	 * Sets the value of the sampleRateRatio property.
	 *
	 * @param value allowed object is {@link SampleRateRatioType }
	 *
	 */
	public void setSampleRateRatio(SampleRateRatioType value) {
		this.sampleRateRatio = value;
	}

	/**
	 * Gets the value of the clockDrift property.
	 *
	 * @return possible object is {@link ChannelType.ClockDrift }
	 *
	 */
	public ChannelType.ClockDrift getClockDrift() {
		return clockDrift;
	}

	/**
	 * Sets the value of the clockDrift property.
	 *
	 * @param value allowed object is {@link ChannelType.ClockDrift }
	 *
	 */
	public void setClockDrift(ChannelType.ClockDrift value) {
		this.clockDrift = value;
	}

	/**
	 * Gets the value of the calibrationUnits property.
	 *
	 * @return possible object is {@link UnitsType }
	 *
	 */
	public UnitsType getCalibrationUnits() {
		return calibrationUnits;
	}

	/**
	 * Sets the value of the calibrationUnits property.
	 *
	 * @param value allowed object is {@link UnitsType }
	 *
	 */
	public void setCalibrationUnits(UnitsType value) {
		this.calibrationUnits = value;
	}

	/**
	 * Gets the value of the sensor property.
	 *
	 * @return possible object is {@link EquipmentType }
	 *
	 */
	public EquipmentType getSensor() {
		return sensor;
	}

	/**
	 * Sets the value of the sensor property.
	 *
	 * @param value allowed object is {@link EquipmentType }
	 *
	 */
	public void setSensor(EquipmentType value) {
		this.sensor = value;
	}

	/**
	 * Gets the value of the preAmplifier property.
	 *
	 * @return possible object is {@link EquipmentType }
	 *
	 */
	public EquipmentType getPreAmplifier() {
		return preAmplifier;
	}

	/**
	 * Sets the value of the preAmplifier property.
	 *
	 * @param value allowed object is {@link EquipmentType }
	 *
	 */
	public void setPreAmplifier(EquipmentType value) {
		this.preAmplifier = value;
	}

	/**
	 * Gets the value of the dataLogger property.
	 *
	 * @return possible object is {@link EquipmentType }
	 *
	 */
	public EquipmentType getDataLogger() {
		return dataLogger;
	}

	/**
	 * Sets the value of the dataLogger property.
	 *
	 * @param value allowed object is {@link EquipmentType }
	 *
	 */
	public void setDataLogger(EquipmentType value) {
		this.dataLogger = value;
	}

	/**
	 * Gets the value of the equipment property.
	 *
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the equipment property.
	 *
	 * <p>
	 * For example, to add a new item, do as follows:
	 * <pre>
	 *    getEquipment().add(newItem);
	 * </pre>
	 *
	 *
	 * <p>
	 * Objects of the following type(s) are allowed in the list
     * {@link EquipmentType }
	 *
	 *
	 */
	public List<EquipmentType> getEquipment() {
		if (equipment == null) {
			equipment = new ArrayList<EquipmentType>();
		}
		return this.equipment;
	}

	/**
	 * Gets the value of the response property.
	 *
	 * @return possible object is {@link ResponseType }
	 *
	 */
	public ResponseType getResponse() {
		return response;
	}

	/**
	 * Sets the value of the response property.
	 *
	 * @param value allowed object is {@link ResponseType }
	 *
	 */
	public void setResponse(ResponseType value) {
		this.response = value;
	}

	/**
	 * Gets the value of the locationCode property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getLocationCode() {
		return locationCode;
	}

	/**
	 * Sets the value of the locationCode property.
	 *
	 * @param value allowed object is {@link String }
	 *
	 */
	public void setLocationCode(String value) {
		this.locationCode = value;
	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 *
	 * <p>
	 * The following schema fragment specifies the expected content contained
	 * within this class.
	 *
	 * <pre>
	 * &lt;complexType&gt;
	 *   &lt;simpleContent&gt;
	 *     &lt;restriction base="&lt;http://www.fdsn.org/xml/station/1&gt;FloatType"&gt;
	 *       &lt;attribute name="unit" type="{http://www.w3.org/2001/XMLSchema}string" fixed="SECONDS/SAMPLE" /&gt;
	 *     &lt;/restriction&gt;
	 *   &lt;/simpleContent&gt;
	 * &lt;/complexType&gt;
	 * </pre>
	 *
	 *
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "")
	public static class ClockDrift
			extends FloatType {

	}

}
