//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//
package gerbera.fdsnws.datamodel;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;

/**
 * Response: coefficients for FIR filter. Laplace transforms or IIR filters can
 * be expressed using type as well but the PolesAndZerosType should be used
 * instead. Corresponds to SEED blockette 54.
 *
 * <p>
 * Java class for CoefficientsType complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType name="CoefficientsType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.fdsn.org/xml/station/1}BaseFilterType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="CfTransferFunctionType"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;enumeration value="ANALOG (RADIANS/SECOND)"/&gt;
 *               &lt;enumeration value="ANALOG (HERTZ)"/&gt;
 *               &lt;enumeration value="DIGITAL"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="Numerator" maxOccurs="unbounded" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;simpleContent&gt;
 *               &lt;extension base="&lt;http://www.fdsn.org/xml/station/1&gt;FloatNoUnitType"&gt;
 *                 &lt;attribute name="number" type="{http://www.fdsn.org/xml/station/1}CounterType" /&gt;
 *               &lt;/extension&gt;
 *             &lt;/simpleContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="Denominator" maxOccurs="unbounded" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;simpleContent&gt;
 *               &lt;extension base="&lt;http://www.fdsn.org/xml/station/1&gt;FloatNoUnitType"&gt;
 *                 &lt;attribute name="number" type="{http://www.fdsn.org/xml/station/1}CounterType" /&gt;
 *               &lt;/extension&gt;
 *             &lt;/simpleContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *       &lt;anyAttribute processContents='lax' namespace='##other'/&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CoefficientsType", propOrder = {
	"cfTransferFunctionType",
	"numerator",
	"denominator"
})
public class CoefficientsType
		extends BaseFilterType {

	@XmlElement(name = "CfTransferFunctionType", required = true)
	protected String cfTransferFunctionType;
	@XmlElement(name = "Numerator")
	protected List<CoefficientsType.Numerator> numerator;
	@XmlElement(name = "Denominator")
	protected List<CoefficientsType.Denominator> denominator;

	/**
	 * Gets the value of the cfTransferFunctionType property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getCfTransferFunctionType() {
		return cfTransferFunctionType;
	}

	/**
	 * Sets the value of the cfTransferFunctionType property.
	 *
	 * @param value allowed object is {@link String }
	 *
	 */
	public void setCfTransferFunctionType(String value) {
		this.cfTransferFunctionType = value;
	}

	/**
	 * Gets the value of the numerator property.
	 *
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the numerator property.
	 *
	 * <p>
	 * For example, to add a new item, do as follows:
	 * <pre>
	 *    getNumerator().add(newItem);
	 * </pre>
	 *
	 *
	 * <p>
	 * Objects of the following type(s) are allowed in the list
     * {@link CoefficientsType.Numerator }
	 *
	 *
	 */
	public List<CoefficientsType.Numerator> getNumerator() {
		if (numerator == null) {
			numerator = new ArrayList<CoefficientsType.Numerator>();
		}
		return this.numerator;
	}

	/**
	 * Gets the value of the denominator property.
	 *
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the denominator property.
	 *
	 * <p>
	 * For example, to add a new item, do as follows:
	 * <pre>
	 *    getDenominator().add(newItem);
	 * </pre>
	 *
	 *
	 * <p>
	 * Objects of the following type(s) are allowed in the list
     * {@link CoefficientsType.Denominator }
	 *
	 *
	 */
	public List<CoefficientsType.Denominator> getDenominator() {
		if (denominator == null) {
			denominator = new ArrayList<CoefficientsType.Denominator>();
		}
		return this.denominator;
	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 *
	 * <p>
	 * The following schema fragment specifies the expected content contained
	 * within this class.
	 *
	 * <pre>
	 * &lt;complexType&gt;
	 *   &lt;simpleContent&gt;
	 *     &lt;extension base="&lt;http://www.fdsn.org/xml/station/1&gt;FloatNoUnitType"&gt;
	 *       &lt;attribute name="number" type="{http://www.fdsn.org/xml/station/1}CounterType" /&gt;
	 *     &lt;/extension&gt;
	 *   &lt;/simpleContent&gt;
	 * &lt;/complexType&gt;
	 * </pre>
	 *
	 *
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "")
	public static class Denominator
			extends FloatNoUnitType {

		@XmlAttribute(name = "number")
		protected BigInteger number;

		/**
		 * Gets the value of the number property.
		 *
		 * @return possible object is {@link BigInteger }
		 *
		 */
		public BigInteger getNumber() {
			return number;
		}

		/**
		 * Sets the value of the number property.
		 *
		 * @param value allowed object is {@link BigInteger }
		 *
		 */
		public void setNumber(BigInteger value) {
			this.number = value;
		}

	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 *
	 * <p>
	 * The following schema fragment specifies the expected content contained
	 * within this class.
	 *
	 * <pre>
	 * &lt;complexType&gt;
	 *   &lt;simpleContent&gt;
	 *     &lt;extension base="&lt;http://www.fdsn.org/xml/station/1&gt;FloatNoUnitType"&gt;
	 *       &lt;attribute name="number" type="{http://www.fdsn.org/xml/station/1}CounterType" /&gt;
	 *     &lt;/extension&gt;
	 *   &lt;/simpleContent&gt;
	 * &lt;/complexType&gt;
	 * </pre>
	 *
	 *
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "")
	public static class Numerator
			extends FloatNoUnitType {

		@XmlAttribute(name = "number")
		protected BigInteger number;

		/**
		 * Gets the value of the number property.
		 *
		 * @return possible object is {@link BigInteger }
		 *
		 */
		public BigInteger getNumber() {
			return number;
		}

		/**
		 * Sets the value of the number property.
		 *
		 * @param value allowed object is {@link BigInteger }
		 *
		 */
		public void setNumber(BigInteger value) {
			this.number = value;
		}

	}

}
