//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//
package gerbera.fdsnws.datamodel;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAnyAttribute;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;

import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.HashMap;
import java.util.Map;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;

/**
 * A type for describing data availability spans, with variable continuity. The
 * time range described may be based on the request parameters that generated
 * the document and not necessarily relate to continuity outside of the range.
 * It may also be a smaller time window than the request depending on the data
 * characteristics.
 *
 * <p>
 * Java class for DataAvailabilitySpanType complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType name="DataAvailabilitySpanType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="start" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" /&gt;
 *       &lt;attribute name="end" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" /&gt;
 *       &lt;attribute name="numberSegments" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
 *       &lt;attribute name="maximumTimeTear" type="{http://www.w3.org/2001/XMLSchema}decimal" /&gt;
 *       &lt;anyAttribute processContents='lax' namespace='##other'/&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DataAvailabilitySpanType")
public class DataAvailabilitySpanType {

	@XmlAttribute(name = "start", required = true)
	@XmlSchemaType(name = "dateTime")
	protected XMLGregorianCalendar start;
	@XmlAttribute(name = "end", required = true)
	@XmlSchemaType(name = "dateTime")
	protected XMLGregorianCalendar end;
	@XmlAttribute(name = "numberSegments", required = true)
	protected BigInteger numberSegments;
	@XmlAttribute(name = "maximumTimeTear")
	protected BigDecimal maximumTimeTear;
	@XmlAnyAttribute
	private Map<QName, String> otherAttributes = new HashMap<QName, String>();

	/**
	 * Gets the value of the start property.
	 *
	 * @return possible object is {@link XMLGregorianCalendar }
	 *
	 */
	public XMLGregorianCalendar getStart() {
		return start;
	}

	/**
	 * Sets the value of the start property.
	 *
	 * @param value allowed object is {@link XMLGregorianCalendar }
	 *
	 */
	public void setStart(XMLGregorianCalendar value) {
		this.start = value;
	}

	/**
	 * Gets the value of the end property.
	 *
	 * @return possible object is {@link XMLGregorianCalendar }
	 *
	 */
	public XMLGregorianCalendar getEnd() {
		return end;
	}

	/**
	 * Sets the value of the end property.
	 *
	 * @param value allowed object is {@link XMLGregorianCalendar }
	 *
	 */
	public void setEnd(XMLGregorianCalendar value) {
		this.end = value;
	}

	/**
	 * Gets the value of the numberSegments property.
	 *
	 * @return possible object is {@link BigInteger }
	 *
	 */
	public BigInteger getNumberSegments() {
		return numberSegments;
	}

	/**
	 * Sets the value of the numberSegments property.
	 *
	 * @param value allowed object is {@link BigInteger }
	 *
	 */
	public void setNumberSegments(BigInteger value) {
		this.numberSegments = value;
	}

	/**
	 * Gets the value of the maximumTimeTear property.
	 *
	 * @return possible object is {@link BigDecimal }
	 *
	 */
	public BigDecimal getMaximumTimeTear() {
		return maximumTimeTear;
	}

	/**
	 * Sets the value of the maximumTimeTear property.
	 *
	 * @param value allowed object is {@link BigDecimal }
	 *
	 */
	public void setMaximumTimeTear(BigDecimal value) {
		this.maximumTimeTear = value;
	}

	/**
	 * Gets a map that contains attributes that aren't bound to any typed
	 * property on this class.
	 *
	 * <p>
	 * the map is keyed by the name of the attribute and the value is the string
	 * value of the attribute.
	 *
	 * the map returned by this method is live, and you can add new attribute by
	 * updating the map directly. Because of this design, there's no setter.
	 *
	 *
	 * @return always non-null
	 */
	public Map<QName, String> getOtherAttributes() {
		return otherAttributes;
	}

}
