//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//
package gerbera.fdsnws.datamodel;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;

import java.math.BigInteger;

/**
 * Corresponds to SEED blockette 57.
 *
 * <p>
 * Java class for DecimationType complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType name="DecimationType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="InputSampleRate" type="{http://www.fdsn.org/xml/station/1}FrequencyType"/&gt;
 *         &lt;element name="Factor" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
 *         &lt;element name="Offset" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
 *         &lt;element name="Delay" type="{http://www.fdsn.org/xml/station/1}FloatType"/&gt;
 *         &lt;element name="Correction" type="{http://www.fdsn.org/xml/station/1}FloatType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DecimationType", propOrder = {
	"inputSampleRate",
	"factor",
	"offset",
	"delay",
	"correction"
})
public class DecimationType {

	@XmlElement(name = "InputSampleRate", required = true)
	protected FrequencyType inputSampleRate;
	@XmlElement(name = "Factor", required = true)
	protected BigInteger factor;
	@XmlElement(name = "Offset", required = true)
	protected BigInteger offset;
	@XmlElement(name = "Delay", required = true)
	protected FloatType delay;
	@XmlElement(name = "Correction", required = true)
	protected FloatType correction;

	/**
	 * Gets the value of the inputSampleRate property.
	 *
	 * @return possible object is {@link FrequencyType }
	 *
	 */
	public FrequencyType getInputSampleRate() {
		return inputSampleRate;
	}

	/**
	 * Sets the value of the inputSampleRate property.
	 *
	 * @param value allowed object is {@link FrequencyType }
	 *
	 */
	public void setInputSampleRate(FrequencyType value) {
		this.inputSampleRate = value;
	}

	/**
	 * Gets the value of the factor property.
	 *
	 * @return possible object is {@link BigInteger }
	 *
	 */
	public BigInteger getFactor() {
		return factor;
	}

	/**
	 * Sets the value of the factor property.
	 *
	 * @param value allowed object is {@link BigInteger }
	 *
	 */
	public void setFactor(BigInteger value) {
		this.factor = value;
	}

	/**
	 * Gets the value of the offset property.
	 *
	 * @return possible object is {@link BigInteger }
	 *
	 */
	public BigInteger getOffset() {
		return offset;
	}

	/**
	 * Sets the value of the offset property.
	 *
	 * @param value allowed object is {@link BigInteger }
	 *
	 */
	public void setOffset(BigInteger value) {
		this.offset = value;
	}

	/**
	 * Gets the value of the delay property.
	 *
	 * @return possible object is {@link FloatType }
	 *
	 */
	public FloatType getDelay() {
		return delay;
	}

	/**
	 * Sets the value of the delay property.
	 *
	 * @param value allowed object is {@link FloatType }
	 *
	 */
	public void setDelay(FloatType value) {
		this.delay = value;
	}

	/**
	 * Gets the value of the correction property.
	 *
	 * @return possible object is {@link FloatType }
	 *
	 */
	public FloatType getCorrection() {
		return correction;
	}

	/**
	 * Sets the value of the correction property.
	 *
	 * @param value allowed object is {@link FloatType }
	 *
	 */
	public void setCorrection(FloatType value) {
		this.correction = value;
	}

}
