//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//
package gerbera.fdsnws.datamodel;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.bind.annotation.XmlType;

/**
 * Complex type for sensitivity and frequency ranges. This complex type can be
 * used to represent both overall sensitivities and individual stage gains. The
 * FrequencyRangeGroup is an optional construct that defines a pass band in
 * Hertz ( FrequencyStart and FrequencyEnd) in which the SensitivityValue is
 * valid within the number of decibels specified in FrequencyDBVariation.
 *
 * <p>
 * Java class for GainType complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType name="GainType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Value" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *         &lt;element name="Frequency" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GainType", propOrder = {
	"value",
	"frequency"
})
@XmlSeeAlso({
	SensitivityType.class
})
public class GainType {

	@XmlElement(name = "Value")
	protected double value;
	@XmlElement(name = "Frequency")
	protected double frequency;

	/**
	 * Gets the value of the value property.
	 *
	 */
	public double getValue() {
		return value;
	}

	/**
	 * Sets the value of the value property.
	 *
	 */
	public void setValue(double value) {
		this.value = value;
	}

	/**
	 * Gets the value of the frequency property.
	 *
	 */
	public double getFrequency() {
		return frequency;
	}

	/**
	 * Sets the value of the frequency property.
	 *
	 */
	public void setFrequency(double value) {
		this.frequency = value;
	}

}
