//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//
package gerbera.fdsnws.datamodel;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * Type for longitude coordinate.
 *
 * <p>
 * Java class for LongitudeType complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType name="LongitudeType"&gt;
 *   &lt;simpleContent&gt;
 *     &lt;extension base="&lt;http://www.fdsn.org/xml/station/1&gt;LongitudeBaseType"&gt;
 *       &lt;attribute name="datum" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" default="WGS84" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/simpleContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LongitudeType")
public class LongitudeType
		extends LongitudeBaseType {

	@XmlAttribute(name = "datum")
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	@XmlSchemaType(name = "NMTOKEN")
	protected String datum;

	/**
	 * Gets the value of the datum property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getDatum() {
		if (datum == null) {
			return "WGS84";
		} else {
			return datum;
		}
	}

	/**
	 * Sets the value of the datum property.
	 *
	 * @param value allowed object is {@link String }
	 *
	 */
	public void setDatum(String value) {
		this.datum = value;
	}

}
