//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//
package gerbera.fdsnws.datamodel;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;

/**
 * This type represents the Network layer, all station metadata is contained
 * within this element. The official name of the network or other descriptive
 * information can be included in the Description element. The Network can
 * contain 0 or more Stations.
 *
 * <p>
 * Java class for NetworkType complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType name="NetworkType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.fdsn.org/xml/station/1}BaseNodeType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Operator" type="{http://www.fdsn.org/xml/station/1}OperatorType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="TotalNumberStations" type="{http://www.fdsn.org/xml/station/1}CounterType" minOccurs="0"/&gt;
 *         &lt;element name="SelectedNumberStations" type="{http://www.fdsn.org/xml/station/1}CounterType" minOccurs="0"/&gt;
 *         &lt;element name="Station" type="{http://www.fdsn.org/xml/station/1}StationType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;anyAttribute processContents='lax' namespace='##other'/&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NetworkType", propOrder = {
	"operator",
	"totalNumberStations",
	"selectedNumberStations",
	"station"
})
public class NetworkType
		extends BaseNodeType {

	@XmlElement(name = "Operator")
	protected List<OperatorType> operator;
	@XmlElement(name = "TotalNumberStations")
	protected BigInteger totalNumberStations;
	@XmlElement(name = "SelectedNumberStations")
	protected BigInteger selectedNumberStations;
	@XmlElement(name = "Station")
	protected List<StationType> station;

	/**
	 * Gets the value of the operator property.
	 *
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the operator property.
	 *
	 * <p>
	 * For example, to add a new item, do as follows:
	 * <pre>
	 *    getOperator().add(newItem);
	 * </pre>
	 *
	 *
	 * <p>
	 * Objects of the following type(s) are allowed in the list
     * {@link OperatorType }
	 *
	 *
	 */
	public List<OperatorType> getOperator() {
		if (operator == null) {
			operator = new ArrayList<OperatorType>();
		}
		return this.operator;
	}

	/**
	 * Gets the value of the totalNumberStations property.
	 *
	 * @return possible object is {@link BigInteger }
	 *
	 */
	public BigInteger getTotalNumberStations() {
		return totalNumberStations;
	}

	/**
	 * Sets the value of the totalNumberStations property.
	 *
	 * @param value allowed object is {@link BigInteger }
	 *
	 */
	public void setTotalNumberStations(BigInteger value) {
		this.totalNumberStations = value;
	}

	/**
	 * Gets the value of the selectedNumberStations property.
	 *
	 * @return possible object is {@link BigInteger }
	 *
	 */
	public BigInteger getSelectedNumberStations() {
		return selectedNumberStations;
	}

	/**
	 * Sets the value of the selectedNumberStations property.
	 *
	 * @param value allowed object is {@link BigInteger }
	 *
	 */
	public void setSelectedNumberStations(BigInteger value) {
		this.selectedNumberStations = value;
	}

	/**
	 * Gets the value of the station property.
	 *
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the station property.
	 *
	 * <p>
	 * For example, to add a new item, do as follows:
	 * <pre>
	 *    getStation().add(newItem);
	 * </pre>
	 *
	 *
	 * <p>
	 * Objects of the following type(s) are allowed in the list
     * {@link StationType }
	 *
	 *
	 */
	public List<StationType> getStation() {
		if (station == null) {
			station = new ArrayList<StationType>();
		}
		return this.station;
	}

}
