//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//
package gerbera.fdsnws.datamodel;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for NominalType.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * <p>
 * <
 * pre>
 * &lt;simpleType name="NominalType"&gt; &lt;restriction
 * base="{http://www.w3.org/2001/XMLSchema}NMTOKEN"&gt; &lt;enumeration
 * value="NOMINAL"/&gt; &lt;enumeration value="CALCULATED"/&gt;
 * &lt;/restriction&gt; &lt;/simpleType&gt;
 * </pre>
 *
 */
@XmlType(name = "NominalType")
@XmlEnum
public enum NominalType {

	NOMINAL,
	CALCULATED;

	public String value() {
		return name();
	}

	public static NominalType fromValue(String v) {
		return valueOf(v);
	}

}
