//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//
package gerbera.fdsnws.datamodel;

import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlElementDecl;
import jakarta.xml.bind.annotation.XmlRegistry;

import javax.xml.namespace.QName;

/**
 * This object contains factory methods for each Java content interface and Java
 * element interface generated in the gerbera.fdsnws.datamodel package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the
 * Java representation for XML content. The Java representation of XML content
 * can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory
 * methods for each of these are provided in this class.
 *
 */
@XmlRegistry
public class ObjectFactory {

	private final static QName _FDSNStationXML_QNAME = new QName("http://www.fdsn.org/xml/station/1", "FDSNStationXML");

	/**
	 * Create a new ObjectFactory that can be used to create new instances of
	 * schema derived classes for package: gerbera.fdsnws.datamodel
	 *
	 */
	public ObjectFactory() {
	}

	/**
	 * Create an instance of {@link PolynomialType }
	 *
	 */
	public PolynomialType createPolynomialType() {
		return new PolynomialType();
	}

	/**
	 * Create an instance of {@link CoefficientsType }
	 *
	 */
	public CoefficientsType createCoefficientsType() {
		return new CoefficientsType();
	}

	/**
	 * Create an instance of {@link FIRType }
	 *
	 */
	public FIRType createFIRType() {
		return new FIRType();
	}

	/**
	 * Create an instance of {@link ChannelType }
	 *
	 */
	public ChannelType createChannelType() {
		return new ChannelType();
	}

	/**
	 * Create an instance of {@link RootType }
	 *
	 */
	public RootType createRootType() {
		return new RootType();
	}

	/**
	 * Create an instance of {@link NetworkType }
	 *
	 */
	public NetworkType createNetworkType() {
		return new NetworkType();
	}

	/**
	 * Create an instance of {@link StationType }
	 *
	 */
	public StationType createStationType() {
		return new StationType();
	}

	/**
	 * Create an instance of {@link GainType }
	 *
	 */
	public GainType createGainType() {
		return new GainType();
	}

	/**
	 * Create an instance of {@link SensitivityType }
	 *
	 */
	public SensitivityType createSensitivityType() {
		return new SensitivityType();
	}

	/**
	 * Create an instance of {@link EquipmentType }
	 *
	 */
	public EquipmentType createEquipmentType() {
		return new EquipmentType();
	}

	/**
	 * Create an instance of {@link ResponseStageType }
	 *
	 */
	public ResponseStageType createResponseStageType() {
		return new ResponseStageType();
	}

	/**
	 * Create an instance of {@link CommentType }
	 *
	 */
	public CommentType createCommentType() {
		return new CommentType();
	}

	/**
	 * Create an instance of {@link PolesZerosType }
	 *
	 */
	public PolesZerosType createPolesZerosType() {
		return new PolesZerosType();
	}

	/**
	 * Create an instance of {@link ResponseListElementType }
	 *
	 */
	public ResponseListElementType createResponseListElementType() {
		return new ResponseListElementType();
	}

	/**
	 * Create an instance of {@link ResponseListType }
	 *
	 */
	public ResponseListType createResponseListType() {
		return new ResponseListType();
	}

	/**
	 * Create an instance of {@link DecimationType }
	 *
	 */
	public DecimationType createDecimationType() {
		return new DecimationType();
	}

	/**
	 * Create an instance of {@link FloatNoUnitType }
	 *
	 */
	public FloatNoUnitType createFloatNoUnitType() {
		return new FloatNoUnitType();
	}

	/**
	 * Create an instance of {@link FloatType }
	 *
	 */
	public FloatType createFloatType() {
		return new FloatType();
	}

	/**
	 * Create an instance of {@link SecondType }
	 *
	 */
	public SecondType createSecondType() {
		return new SecondType();
	}

	/**
	 * Create an instance of {@link VoltageType }
	 *
	 */
	public VoltageType createVoltageType() {
		return new VoltageType();
	}

	/**
	 * Create an instance of {@link AngleType }
	 *
	 */
	public AngleType createAngleType() {
		return new AngleType();
	}

	/**
	 * Create an instance of {@link LatitudeBaseType }
	 *
	 */
	public LatitudeBaseType createLatitudeBaseType() {
		return new LatitudeBaseType();
	}

	/**
	 * Create an instance of {@link LatitudeType }
	 *
	 */
	public LatitudeType createLatitudeType() {
		return new LatitudeType();
	}

	/**
	 * Create an instance of {@link LongitudeBaseType }
	 *
	 */
	public LongitudeBaseType createLongitudeBaseType() {
		return new LongitudeBaseType();
	}

	/**
	 * Create an instance of {@link LongitudeType }
	 *
	 */
	public LongitudeType createLongitudeType() {
		return new LongitudeType();
	}

	/**
	 * Create an instance of {@link AzimuthType }
	 *
	 */
	public AzimuthType createAzimuthType() {
		return new AzimuthType();
	}

	/**
	 * Create an instance of {@link DipType }
	 *
	 */
	public DipType createDipType() {
		return new DipType();
	}

	/**
	 * Create an instance of {@link DistanceType }
	 *
	 */
	public DistanceType createDistanceType() {
		return new DistanceType();
	}

	/**
	 * Create an instance of {@link FrequencyType }
	 *
	 */
	public FrequencyType createFrequencyType() {
		return new FrequencyType();
	}

	/**
	 * Create an instance of {@link SampleRateType }
	 *
	 */
	public SampleRateType createSampleRateType() {
		return new SampleRateType();
	}

	/**
	 * Create an instance of {@link SampleRateRatioType }
	 *
	 */
	public SampleRateRatioType createSampleRateRatioType() {
		return new SampleRateRatioType();
	}

	/**
	 * Create an instance of {@link PoleZeroType }
	 *
	 */
	public PoleZeroType createPoleZeroType() {
		return new PoleZeroType();
	}

	/**
	 * Create an instance of {@link OperatorType }
	 *
	 */
	public OperatorType createOperatorType() {
		return new OperatorType();
	}

	/**
	 * Create an instance of {@link PersonType }
	 *
	 */
	public PersonType createPersonType() {
		return new PersonType();
	}

	/**
	 * Create an instance of {@link SiteType }
	 *
	 */
	public SiteType createSiteType() {
		return new SiteType();
	}

	/**
	 * Create an instance of {@link ExternalReferenceType }
	 *
	 */
	public ExternalReferenceType createExternalReferenceType() {
		return new ExternalReferenceType();
	}

	/**
	 * Create an instance of {@link PhoneNumberType }
	 *
	 */
	public PhoneNumberType createPhoneNumberType() {
		return new PhoneNumberType();
	}

	/**
	 * Create an instance of {@link UnitsType }
	 *
	 */
	public UnitsType createUnitsType() {
		return new UnitsType();
	}

	/**
	 * Create an instance of {@link IdentifierType }
	 *
	 */
	public IdentifierType createIdentifierType() {
		return new IdentifierType();
	}

	/**
	 * Create an instance of {@link BaseFilterType }
	 *
	 */
	public BaseFilterType createBaseFilterType() {
		return new BaseFilterType();
	}

	/**
	 * Create an instance of {@link ResponseType }
	 *
	 */
	public ResponseType createResponseType() {
		return new ResponseType();
	}

	/**
	 * Create an instance of {@link BaseNodeType }
	 *
	 */
	public BaseNodeType createBaseNodeType() {
		return new BaseNodeType();
	}

	/**
	 * Create an instance of {@link DataAvailabilityExtentType }
	 *
	 */
	public DataAvailabilityExtentType createDataAvailabilityExtentType() {
		return new DataAvailabilityExtentType();
	}

	/**
	 * Create an instance of {@link DataAvailabilitySpanType }
	 *
	 */
	public DataAvailabilitySpanType createDataAvailabilitySpanType() {
		return new DataAvailabilitySpanType();
	}

	/**
	 * Create an instance of {@link DataAvailabilityType }
	 *
	 */
	public DataAvailabilityType createDataAvailabilityType() {
		return new DataAvailabilityType();
	}

	/**
	 * Create an instance of {@link PolynomialType.Coefficient }
	 *
	 */
	public PolynomialType.Coefficient createPolynomialTypeCoefficient() {
		return new PolynomialType.Coefficient();
	}

	/**
	 * Create an instance of {@link CoefficientsType.Numerator }
	 *
	 */
	public CoefficientsType.Numerator createCoefficientsTypeNumerator() {
		return new CoefficientsType.Numerator();
	}

	/**
	 * Create an instance of {@link CoefficientsType.Denominator }
	 *
	 */
	public CoefficientsType.Denominator createCoefficientsTypeDenominator() {
		return new CoefficientsType.Denominator();
	}

	/**
	 * Create an instance of {@link FIRType.NumeratorCoefficient }
	 *
	 */
	public FIRType.NumeratorCoefficient createFIRTypeNumeratorCoefficient() {
		return new FIRType.NumeratorCoefficient();
	}

	/**
	 * Create an instance of {@link ChannelType.ClockDrift }
	 *
	 */
	public ChannelType.ClockDrift createChannelTypeClockDrift() {
		return new ChannelType.ClockDrift();
	}

	/**
	 * Create an instance of
	 * {@link JAXBElement }{@code <}{@link RootType }{@code >}
	 *
	 * @param value Java instance representing xml element's value.
	 * @return the new instance of
	 * {@link JAXBElement }{@code <}{@link RootType }{@code >}
	 */
	@XmlElementDecl(namespace = "http://www.fdsn.org/xml/station/1", name = "FDSNStationXML")
	public JAXBElement<RootType> createFDSNStationXML(RootType value) {
		return new JAXBElement<RootType>(_FDSNStationXML_QNAME, RootType.class, null, value);
	}

}
