//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema.
//
@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://www.fdsn.org/xml/station/1", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package gerbera.fdsnws.datamodel;
