//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//
package gerbera.fdsnws.datamodel;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;

import java.math.BigInteger;

/**
 * <p>
 * Java class for PhoneNumberType complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType name="PhoneNumberType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="CountryCode" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *         &lt;element name="AreaCode" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
 *         &lt;element name="PhoneNumber"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;pattern value="[0-9]+-[0-9]+"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="description" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PhoneNumberType", propOrder = {
	"countryCode",
	"areaCode",
	"phoneNumber"
})
public class PhoneNumberType {

	@XmlElement(name = "CountryCode")
	protected BigInteger countryCode;
	@XmlElement(name = "AreaCode", required = true)
	protected BigInteger areaCode;
	@XmlElement(name = "PhoneNumber", required = true)
	protected String phoneNumber;
	@XmlAttribute(name = "description")
	protected String description;

	/**
	 * Gets the value of the countryCode property.
	 *
	 * @return possible object is {@link BigInteger }
	 *
	 */
	public BigInteger getCountryCode() {
		return countryCode;
	}

	/**
	 * Sets the value of the countryCode property.
	 *
	 * @param value allowed object is {@link BigInteger }
	 *
	 */
	public void setCountryCode(BigInteger value) {
		this.countryCode = value;
	}

	/**
	 * Gets the value of the areaCode property.
	 *
	 * @return possible object is {@link BigInteger }
	 *
	 */
	public BigInteger getAreaCode() {
		return areaCode;
	}

	/**
	 * Sets the value of the areaCode property.
	 *
	 * @param value allowed object is {@link BigInteger }
	 *
	 */
	public void setAreaCode(BigInteger value) {
		this.areaCode = value;
	}

	/**
	 * Gets the value of the phoneNumber property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getPhoneNumber() {
		return phoneNumber;
	}

	/**
	 * Sets the value of the phoneNumber property.
	 *
	 * @param value allowed object is {@link String }
	 *
	 */
	public void setPhoneNumber(String value) {
		this.phoneNumber = value;
	}

	/**
	 * Gets the value of the description property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * Sets the value of the description property.
	 *
	 * @param value allowed object is {@link String }
	 *
	 */
	public void setDescription(String value) {
		this.description = value;
	}

}
