//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//
package gerbera.fdsnws.datamodel;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;

import java.util.ArrayList;
import java.util.List;

/**
 * Response: complex poles and zeros. Corresponds to SEED blockette 53.
 *
 * <p>
 * Java class for PolesZerosType complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType name="PolesZerosType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.fdsn.org/xml/station/1}BaseFilterType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="PzTransferFunctionType"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;enumeration value="LAPLACE (RADIANS/SECOND)"/&gt;
 *               &lt;enumeration value="LAPLACE (HERTZ)"/&gt;
 *               &lt;enumeration value="DIGITAL (Z-TRANSFORM)"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="NormalizationFactor" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *         &lt;element name="NormalizationFrequency" type="{http://www.fdsn.org/xml/station/1}FrequencyType"/&gt;
 *         &lt;element name="Zero" type="{http://www.fdsn.org/xml/station/1}PoleZeroType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="Pole" type="{http://www.fdsn.org/xml/station/1}PoleZeroType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;anyAttribute processContents='lax' namespace='##other'/&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PolesZerosType", propOrder = {
	"pzTransferFunctionType",
	"normalizationFactor",
	"normalizationFrequency",
	"zero",
	"pole"
})
public class PolesZerosType
		extends BaseFilterType {

	@XmlElement(name = "PzTransferFunctionType", required = true)
	protected String pzTransferFunctionType;
	@XmlElement(name = "NormalizationFactor", defaultValue = "1.0")
	protected double normalizationFactor;
	@XmlElement(name = "NormalizationFrequency", required = true)
	protected FrequencyType normalizationFrequency;
	@XmlElement(name = "Zero")
	protected List<PoleZeroType> zero;
	@XmlElement(name = "Pole")
	protected List<PoleZeroType> pole;

	/**
	 * Gets the value of the pzTransferFunctionType property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getPzTransferFunctionType() {
		return pzTransferFunctionType;
	}

	/**
	 * Sets the value of the pzTransferFunctionType property.
	 *
	 * @param value allowed object is {@link String }
	 *
	 */
	public void setPzTransferFunctionType(String value) {
		this.pzTransferFunctionType = value;
	}

	/**
	 * Gets the value of the normalizationFactor property.
	 *
	 */
	public double getNormalizationFactor() {
		return normalizationFactor;
	}

	/**
	 * Sets the value of the normalizationFactor property.
	 *
	 */
	public void setNormalizationFactor(double value) {
		this.normalizationFactor = value;
	}

	/**
	 * Gets the value of the normalizationFrequency property.
	 *
	 * @return possible object is {@link FrequencyType }
	 *
	 */
	public FrequencyType getNormalizationFrequency() {
		return normalizationFrequency;
	}

	/**
	 * Sets the value of the normalizationFrequency property.
	 *
	 * @param value allowed object is {@link FrequencyType }
	 *
	 */
	public void setNormalizationFrequency(FrequencyType value) {
		this.normalizationFrequency = value;
	}

	/**
	 * Gets the value of the zero property.
	 *
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the zero property.
	 *
	 * <p>
	 * For example, to add a new item, do as follows:
	 * <pre>
	 *    getZero().add(newItem);
	 * </pre>
	 *
	 *
	 * <p>
	 * Objects of the following type(s) are allowed in the list
     * {@link PoleZeroType }
	 *
	 *
	 */
	public List<PoleZeroType> getZero() {
		if (zero == null) {
			zero = new ArrayList<PoleZeroType>();
		}
		return this.zero;
	}

	/**
	 * Gets the value of the pole property.
	 *
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the pole property.
	 *
	 * <p>
	 * For example, to add a new item, do as follows:
	 * <pre>
	 *    getPole().add(newItem);
	 * </pre>
	 *
	 *
	 * <p>
	 * Objects of the following type(s) are allowed in the list
     * {@link PoleZeroType }
	 *
	 *
	 */
	public List<PoleZeroType> getPole() {
		if (pole == null) {
			pole = new ArrayList<PoleZeroType>();
		}
		return this.pole;
	}

}
