//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//
package gerbera.fdsnws.datamodel;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;

import java.math.BigInteger;

/**
 * Complex numbers used as poles or zeros in channel response.
 *
 * <p>
 * Java class for PoleZeroType complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType name="PoleZeroType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Real" type="{http://www.fdsn.org/xml/station/1}FloatNoUnitType"/&gt;
 *         &lt;element name="Imaginary" type="{http://www.fdsn.org/xml/station/1}FloatNoUnitType"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="number" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PoleZeroType", propOrder = {
	"real",
	"imaginary"
})
public class PoleZeroType {

	@XmlElement(name = "Real", required = true)
	protected FloatNoUnitType real;
	@XmlElement(name = "Imaginary", required = true)
	protected FloatNoUnitType imaginary;
	@XmlAttribute(name = "number")
	protected BigInteger number;

	/**
	 * Gets the value of the real property.
	 *
	 * @return possible object is {@link FloatNoUnitType }
	 *
	 */
	public FloatNoUnitType getReal() {
		return real;
	}

	/**
	 * Sets the value of the real property.
	 *
	 * @param value allowed object is {@link FloatNoUnitType }
	 *
	 */
	public void setReal(FloatNoUnitType value) {
		this.real = value;
	}

	/**
	 * Gets the value of the imaginary property.
	 *
	 * @return possible object is {@link FloatNoUnitType }
	 *
	 */
	public FloatNoUnitType getImaginary() {
		return imaginary;
	}

	/**
	 * Sets the value of the imaginary property.
	 *
	 * @param value allowed object is {@link FloatNoUnitType }
	 *
	 */
	public void setImaginary(FloatNoUnitType value) {
		this.imaginary = value;
	}

	/**
	 * Gets the value of the number property.
	 *
	 * @return possible object is {@link BigInteger }
	 *
	 */
	public BigInteger getNumber() {
		return number;
	}

	/**
	 * Sets the value of the number property.
	 *
	 * @param value allowed object is {@link BigInteger }
	 *
	 */
	public void setNumber(BigInteger value) {
		this.number = value;
	}

}
