//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//
package gerbera.fdsnws.datamodel;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;

/**
 * Response: expressed as a polynomial (allows non-linear sensors to be
 * described). Corresponds to SEED blockette 62. Can be used to describe a stage
 * of acquisition or a complete system.
 *
 * <p>
 * Java class for PolynomialType complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType name="PolynomialType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.fdsn.org/xml/station/1}BaseFilterType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ApproximationType"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;enumeration value="MACLAURIN"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="FrequencyLowerBound" type="{http://www.fdsn.org/xml/station/1}FrequencyType"/&gt;
 *         &lt;element name="FrequencyUpperBound" type="{http://www.fdsn.org/xml/station/1}FrequencyType"/&gt;
 *         &lt;element name="ApproximationLowerBound" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *         &lt;element name="ApproximationUpperBound" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *         &lt;element name="MaximumError" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *         &lt;element name="Coefficient" maxOccurs="unbounded"&gt;
 *           &lt;complexType&gt;
 *             &lt;simpleContent&gt;
 *               &lt;extension base="&lt;http://www.fdsn.org/xml/station/1&gt;FloatNoUnitType"&gt;
 *                 &lt;attribute name="number" type="{http://www.fdsn.org/xml/station/1}CounterType" /&gt;
 *               &lt;/extension&gt;
 *             &lt;/simpleContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *       &lt;anyAttribute processContents='lax' namespace='##other'/&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PolynomialType", propOrder = {
	"approximationType",
	"frequencyLowerBound",
	"frequencyUpperBound",
	"approximationLowerBound",
	"approximationUpperBound",
	"maximumError",
	"coefficient"
})
public class PolynomialType
		extends BaseFilterType {

	@XmlElement(name = "ApproximationType", required = true, defaultValue = "MACLAURIN")
	protected String approximationType;
	@XmlElement(name = "FrequencyLowerBound", required = true)
	protected FrequencyType frequencyLowerBound;
	@XmlElement(name = "FrequencyUpperBound", required = true)
	protected FrequencyType frequencyUpperBound;
	@XmlElement(name = "ApproximationLowerBound")
	protected double approximationLowerBound;
	@XmlElement(name = "ApproximationUpperBound")
	protected double approximationUpperBound;
	@XmlElement(name = "MaximumError")
	protected double maximumError;
	@XmlElement(name = "Coefficient", required = true)
	protected List<PolynomialType.Coefficient> coefficient;

	/**
	 * Gets the value of the approximationType property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getApproximationType() {
		return approximationType;
	}

	/**
	 * Sets the value of the approximationType property.
	 *
	 * @param value allowed object is {@link String }
	 *
	 */
	public void setApproximationType(String value) {
		this.approximationType = value;
	}

	/**
	 * Gets the value of the frequencyLowerBound property.
	 *
	 * @return possible object is {@link FrequencyType }
	 *
	 */
	public FrequencyType getFrequencyLowerBound() {
		return frequencyLowerBound;
	}

	/**
	 * Sets the value of the frequencyLowerBound property.
	 *
	 * @param value allowed object is {@link FrequencyType }
	 *
	 */
	public void setFrequencyLowerBound(FrequencyType value) {
		this.frequencyLowerBound = value;
	}

	/**
	 * Gets the value of the frequencyUpperBound property.
	 *
	 * @return possible object is {@link FrequencyType }
	 *
	 */
	public FrequencyType getFrequencyUpperBound() {
		return frequencyUpperBound;
	}

	/**
	 * Sets the value of the frequencyUpperBound property.
	 *
	 * @param value allowed object is {@link FrequencyType }
	 *
	 */
	public void setFrequencyUpperBound(FrequencyType value) {
		this.frequencyUpperBound = value;
	}

	/**
	 * Gets the value of the approximationLowerBound property.
	 *
	 */
	public double getApproximationLowerBound() {
		return approximationLowerBound;
	}

	/**
	 * Sets the value of the approximationLowerBound property.
	 *
	 */
	public void setApproximationLowerBound(double value) {
		this.approximationLowerBound = value;
	}

	/**
	 * Gets the value of the approximationUpperBound property.
	 *
	 */
	public double getApproximationUpperBound() {
		return approximationUpperBound;
	}

	/**
	 * Sets the value of the approximationUpperBound property.
	 *
	 */
	public void setApproximationUpperBound(double value) {
		this.approximationUpperBound = value;
	}

	/**
	 * Gets the value of the maximumError property.
	 *
	 */
	public double getMaximumError() {
		return maximumError;
	}

	/**
	 * Sets the value of the maximumError property.
	 *
	 */
	public void setMaximumError(double value) {
		this.maximumError = value;
	}

	/**
	 * Gets the value of the coefficient property.
	 *
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the coefficient property.
	 *
	 * <p>
	 * For example, to add a new item, do as follows:
	 * <pre>
	 *    getCoefficient().add(newItem);
	 * </pre>
	 *
	 *
	 * <p>
	 * Objects of the following type(s) are allowed in the list
     * {@link PolynomialType.Coefficient }
	 *
	 *
	 */
	public List<PolynomialType.Coefficient> getCoefficient() {
		if (coefficient == null) {
			coefficient = new ArrayList<PolynomialType.Coefficient>();
		}
		return this.coefficient;
	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 *
	 * <p>
	 * The following schema fragment specifies the expected content contained
	 * within this class.
	 *
	 * <pre>
	 * &lt;complexType&gt;
	 *   &lt;simpleContent&gt;
	 *     &lt;extension base="&lt;http://www.fdsn.org/xml/station/1&gt;FloatNoUnitType"&gt;
	 *       &lt;attribute name="number" type="{http://www.fdsn.org/xml/station/1}CounterType" /&gt;
	 *     &lt;/extension&gt;
	 *   &lt;/simpleContent&gt;
	 * &lt;/complexType&gt;
	 * </pre>
	 *
	 *
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "")
	public static class Coefficient
			extends FloatNoUnitType {

		@XmlAttribute(name = "number")
		protected BigInteger number;

		/**
		 * Gets the value of the number property.
		 *
		 * @return possible object is {@link BigInteger }
		 *
		 */
		public BigInteger getNumber() {
			return number;
		}

		/**
		 * Sets the value of the number property.
		 *
		 * @param value allowed object is {@link BigInteger }
		 *
		 */
		public void setNumber(BigInteger value) {
			this.number = value;
		}

	}

}
