//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//
package gerbera.fdsnws.datamodel;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;

import java.util.ArrayList;
import java.util.List;

/**
 * Response: list of frequency, amplitude and phase values. Corresponds to SEED
 * blockette 55.
 *
 * <p>
 * Java class for ResponseListType complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType name="ResponseListType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.fdsn.org/xml/station/1}BaseFilterType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ResponseListElement" type="{http://www.fdsn.org/xml/station/1}ResponseListElementType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;anyAttribute processContents='lax' namespace='##other'/&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ResponseListType", propOrder = {
	"responseListElement"
})
public class ResponseListType
		extends BaseFilterType {

	@XmlElement(name = "ResponseListElement")
	protected List<ResponseListElementType> responseListElement;

	/**
	 * Gets the value of the responseListElement property.
	 *
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the responseListElement property.
	 *
	 * <p>
	 * For example, to add a new item, do as follows:
	 * <pre>
	 *    getResponseListElement().add(newItem);
	 * </pre>
	 *
	 *
	 * <p>
	 * Objects of the following type(s) are allowed in the list
     * {@link ResponseListElementType }
	 *
	 *
	 */
	public List<ResponseListElementType> getResponseListElement() {
		if (responseListElement == null) {
			responseListElement = new ArrayList<ResponseListElementType>();
		}
		return this.responseListElement;
	}

}
