//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema.  
//
package gerbera.fdsnws.datamodel;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAnyAttribute;
import jakarta.xml.bind.annotation.XmlAnyElement;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.xml.namespace.QName;

import org.w3c.dom.Element;

/**
 * This complex type represents channel response and covers SEED blockettes 53
 * to 56.
 *
 * <p>
 * Java class for ResponseStageType complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType name="ResponseStageType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;choice&gt;
 *           &lt;sequence&gt;
 *             &lt;choice&gt;
 *               &lt;element name="PolesZeros" type="{http://www.fdsn.org/xml/station/1}PolesZerosType" minOccurs="0"/&gt;
 *               &lt;element name="Coefficients" type="{http://www.fdsn.org/xml/station/1}CoefficientsType" minOccurs="0"/&gt;
 *               &lt;element name="ResponseList" type="{http://www.fdsn.org/xml/station/1}ResponseListType" minOccurs="0"/&gt;
 *               &lt;element name="FIR" type="{http://www.fdsn.org/xml/station/1}FIRType" minOccurs="0"/&gt;
 *             &lt;/choice&gt;
 *             &lt;element name="Decimation" type="{http://www.fdsn.org/xml/station/1}DecimationType" minOccurs="0"/&gt;
 *             &lt;element name="StageGain" type="{http://www.fdsn.org/xml/station/1}GainType"/&gt;
 *           &lt;/sequence&gt;
 *           &lt;element name="Polynomial" type="{http://www.fdsn.org/xml/station/1}PolynomialType"/&gt;
 *         &lt;/choice&gt;
 *         &lt;any processContents='lax' namespace='##other' maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="number" use="required" type="{http://www.fdsn.org/xml/station/1}CounterType" /&gt;
 *       &lt;attribute name="resourceId" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;anyAttribute processContents='lax' namespace='##other'/&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ResponseStageType", propOrder = {
	"polesZeros",
	"coefficients",
	"responseList",
	"fir",
	"decimation",
	"stageGain",
	"polynomial",
	"any"
})
public class ResponseStageType {

	@XmlElement(name = "PolesZeros")
	protected PolesZerosType polesZeros;
	@XmlElement(name = "Coefficients")
	protected CoefficientsType coefficients;
	@XmlElement(name = "ResponseList")
	protected ResponseListType responseList;
	@XmlElement(name = "FIR")
	protected FIRType fir;
	@XmlElement(name = "Decimation")
	protected DecimationType decimation;
	@XmlElement(name = "StageGain")
	protected GainType stageGain;
	@XmlElement(name = "Polynomial")
	protected PolynomialType polynomial;
	@XmlAnyElement(lax = true)
	protected List<Object> any;
	@XmlAttribute(name = "number", required = true)
	protected BigInteger number;
	@XmlAttribute(name = "resourceId")
	protected String resourceId;
	@XmlAnyAttribute
	private Map<QName, String> otherAttributes = new HashMap<QName, String>();

	/**
	 * Gets the value of the polesZeros property.
	 *
	 * @return possible object is {@link PolesZerosType }
	 *
	 */
	public PolesZerosType getPolesZeros() {
		return polesZeros;
	}

	/**
	 * Sets the value of the polesZeros property.
	 *
	 * @param value allowed object is {@link PolesZerosType }
	 *
	 */
	public void setPolesZeros(PolesZerosType value) {
		this.polesZeros = value;
	}

	/**
	 * Gets the value of the coefficients property.
	 *
	 * @return possible object is {@link CoefficientsType }
	 *
	 */
	public CoefficientsType getCoefficients() {
		return coefficients;
	}

	/**
	 * Sets the value of the coefficients property.
	 *
	 * @param value allowed object is {@link CoefficientsType }
	 *
	 */
	public void setCoefficients(CoefficientsType value) {
		this.coefficients = value;
	}

	/**
	 * Gets the value of the responseList property.
	 *
	 * @return possible object is {@link ResponseListType }
	 *
	 */
	public ResponseListType getResponseList() {
		return responseList;
	}

	/**
	 * Sets the value of the responseList property.
	 *
	 * @param value allowed object is {@link ResponseListType }
	 *
	 */
	public void setResponseList(ResponseListType value) {
		this.responseList = value;
	}

	/**
	 * Gets the value of the fir property.
	 *
	 * @return possible object is {@link FIRType }
	 *
	 */
	public FIRType getFIR() {
		return fir;
	}

	/**
	 * Sets the value of the fir property.
	 *
	 * @param value allowed object is {@link FIRType }
	 *
	 */
	public void setFIR(FIRType value) {
		this.fir = value;
	}

	/**
	 * Gets the value of the decimation property.
	 *
	 * @return possible object is {@link DecimationType }
	 *
	 */
	public DecimationType getDecimation() {
		return decimation;
	}

	/**
	 * Sets the value of the decimation property.
	 *
	 * @param value allowed object is {@link DecimationType }
	 *
	 */
	public void setDecimation(DecimationType value) {
		this.decimation = value;
	}

	/**
	 * Gets the value of the stageGain property.
	 *
	 * @return possible object is {@link GainType }
	 *
	 */
	public GainType getStageGain() {
		return stageGain;
	}

	/**
	 * Sets the value of the stageGain property.
	 *
	 * @param value allowed object is {@link GainType }
	 *
	 */
	public void setStageGain(GainType value) {
		this.stageGain = value;
	}

	/**
	 * Gets the value of the polynomial property.
	 *
	 * @return possible object is {@link PolynomialType }
	 *
	 */
	public PolynomialType getPolynomial() {
		return polynomial;
	}

	/**
	 * Sets the value of the polynomial property.
	 *
	 * @param value allowed object is {@link PolynomialType }
	 *
	 */
	public void setPolynomial(PolynomialType value) {
		this.polynomial = value;
	}

	/**
	 * Gets the value of the any property.
	 *
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the any property.
	 *
	 * <p>
	 * For example, to add a new item, do as follows:
	 * <pre>
	 *    getAny().add(newItem);
	 * </pre>
	 *
	 *
	 * <p>
	 * Objects of the following type(s) are allowed in the list null	null	null	 {@link Element }
     * {@link Object }
	 *
	 *
	 */
	public List<Object> getAny() {
		if (any == null) {
			any = new ArrayList<Object>();
		}
		return this.any;
	}

	/**
	 * Gets the value of the number property.
	 *
	 * @return possible object is {@link BigInteger }
	 *
	 */
	public BigInteger getNumber() {
		return number;
	}

	/**
	 * Sets the value of the number property.
	 *
	 * @param value allowed object is {@link BigInteger }
	 *
	 */
	public void setNumber(BigInteger value) {
		this.number = value;
	}

	/**
	 * Gets the value of the resourceId property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getResourceId() {
		return resourceId;
	}

	/**
	 * Sets the value of the resourceId property.
	 *
	 * @param value allowed object is {@link String }
	 *
	 */
	public void setResourceId(String value) {
		this.resourceId = value;
	}

	/**
	 * Gets a map that contains attributes that aren't bound to any typed
	 * property on this class.
	 *
	 * <p>
	 * the map is keyed by the name of the attribute and the value is the string
	 * value of the attribute.
	 *
	 * the map returned by this method is live, and you can add new attribute by
	 * updating the map directly. Because of this design, there's no setter.
	 *
	 *
	 * @return always non-null
	 */
	public Map<QName, String> getOtherAttributes() {
		return otherAttributes;
	}

}
