//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//
package gerbera.fdsnws.datamodel;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for ResponseListElementType complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType name="ResponseListElementType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Frequency" type="{http://www.fdsn.org/xml/station/1}FrequencyType"/&gt;
 *         &lt;element name="Amplitude" type="{http://www.fdsn.org/xml/station/1}FloatType"/&gt;
 *         &lt;element name="Phase" type="{http://www.fdsn.org/xml/station/1}AngleType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ResponseListElementType", propOrder = {
	"frequency",
	"amplitude",
	"phase"
})
public class ResponseListElementType {

	@XmlElement(name = "Frequency", required = true)
	protected FrequencyType frequency;
	@XmlElement(name = "Amplitude", required = true)
	protected FloatType amplitude;
	@XmlElement(name = "Phase", required = true)
	protected AngleType phase;

	/**
	 * Gets the value of the frequency property.
	 *
	 * @return possible object is {@link FrequencyType }
	 *
	 */
	public FrequencyType getFrequency() {
		return frequency;
	}

	/**
	 * Sets the value of the frequency property.
	 *
	 * @param value allowed object is {@link FrequencyType }
	 *
	 */
	public void setFrequency(FrequencyType value) {
		this.frequency = value;
	}

	/**
	 * Gets the value of the amplitude property.
	 *
	 * @return possible object is {@link FloatType }
	 *
	 */
	public FloatType getAmplitude() {
		return amplitude;
	}

	/**
	 * Sets the value of the amplitude property.
	 *
	 * @param value allowed object is {@link FloatType }
	 *
	 */
	public void setAmplitude(FloatType value) {
		this.amplitude = value;
	}

	/**
	 * Gets the value of the phase property.
	 *
	 * @return possible object is {@link AngleType }
	 *
	 */
	public AngleType getPhase() {
		return phase;
	}

	/**
	 * Sets the value of the phase property.
	 *
	 * @param value allowed object is {@link AngleType }
	 *
	 */
	public void setPhase(AngleType value) {
		this.phase = value;
	}

}
