//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//
package gerbera.fdsnws.datamodel;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAnyAttribute;
import jakarta.xml.bind.annotation.XmlAnyElement;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;

import org.w3c.dom.Element;

/**
 * Top-level type for Station XML. Required fields are Source (network ID of the
 * institution sending the message), Created (creation time of the document) and
 * one or more Network containers.
 *
 * <p>
 * Java class for RootType complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType name="RootType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Source" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Sender" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Module" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ModuleURI" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/&gt;
 *         &lt;element name="Created" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
 *         &lt;element name="Network" type="{http://www.fdsn.org/xml/station/1}NetworkType" maxOccurs="unbounded"/&gt;
 *         &lt;any processContents='lax' namespace='##other' maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="schemaVersion" use="required" type="{http://www.w3.org/2001/XMLSchema}decimal" /&gt;
 *       &lt;anyAttribute processContents='lax' namespace='##other'/&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlRootElement(name = "FDSNStationXML")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RootType", propOrder = {
	"source",
	"sender",
	"module",
	"moduleURI",
	"created",
	"network",
	"any"
})
public class RootType {

	@XmlElement(name = "Source", required = true)
	protected String source;
	@XmlElement(name = "Sender")
	protected String sender;
	@XmlElement(name = "Module")
	protected String module;
	@XmlElement(name = "ModuleURI")
	@XmlSchemaType(name = "anyURI")
	protected String moduleURI;
	@XmlElement(name = "Created", required = true)
	@XmlSchemaType(name = "dateTime")
	protected XMLGregorianCalendar created;
	@XmlElement(name = "Network", required = true)
	protected List<NetworkType> network;
	@XmlAnyElement(lax = true)
	protected List<Object> any;
	@XmlAttribute(name = "schemaVersion", required = true)
	protected BigDecimal schemaVersion;
	@XmlAnyAttribute
	private Map<QName, String> otherAttributes = new HashMap<QName, String>();

	/**
	 * Gets the value of the source property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getSource() {
		return source;
	}

	/**
	 * Sets the value of the source property.
	 *
	 * @param value allowed object is {@link String }
	 *
	 */
	public void setSource(String value) {
		this.source = value;
	}

	/**
	 * Gets the value of the sender property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getSender() {
		return sender;
	}

	/**
	 * Sets the value of the sender property.
	 *
	 * @param value allowed object is {@link String }
	 *
	 */
	public void setSender(String value) {
		this.sender = value;
	}

	/**
	 * Gets the value of the module property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getModule() {
		return module;
	}

	/**
	 * Sets the value of the module property.
	 *
	 * @param value allowed object is {@link String }
	 *
	 */
	public void setModule(String value) {
		this.module = value;
	}

	/**
	 * Gets the value of the moduleURI property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getModuleURI() {
		return moduleURI;
	}

	/**
	 * Sets the value of the moduleURI property.
	 *
	 * @param value allowed object is {@link String }
	 *
	 */
	public void setModuleURI(String value) {
		this.moduleURI = value;
	}

	/**
	 * Gets the value of the created property.
	 *
	 * @return possible object is {@link XMLGregorianCalendar }
	 *
	 */
	public XMLGregorianCalendar getCreated() {
		return created;
	}

	/**
	 * Sets the value of the created property.
	 *
	 * @param value allowed object is {@link XMLGregorianCalendar }
	 *
	 */
	public void setCreated(XMLGregorianCalendar value) {
		this.created = value;
	}

	/**
	 * Gets the value of the network property.
	 *
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the network property.
	 *
	 * <p>
	 * For example, to add a new item, do as follows:
	 * <pre>
	 *    getNetwork().add(newItem);
	 * </pre>
	 *
	 *
	 * <p>
	 * Objects of the following type(s) are allowed in the list
     * {@link NetworkType }
	 *
	 *
	 */
	public List<NetworkType> getNetwork() {
		if (network == null) {
			network = new ArrayList<NetworkType>();
		}
		return this.network;
	}

	/**
	 * Gets the value of the any property.
	 *
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the any property.
	 *
	 * <p>
	 * For example, to add a new item, do as follows:
	 * <pre>
	 *    getAny().add(newItem);
	 * </pre>
	 *
	 *
	 * <p>
	 * Objects of the following type(s) are allowed in the list null	null	null	 {@link Element }
     * {@link Object }
	 *
	 *
	 */
	public List<Object> getAny() {
		if (any == null) {
			any = new ArrayList<Object>();
		}
		return this.any;
	}

	/**
	 * Gets the value of the schemaVersion property.
	 *
	 * @return possible object is {@link BigDecimal }
	 *
	 */
	public BigDecimal getSchemaVersion() {
		return schemaVersion;
	}

	/**
	 * Sets the value of the schemaVersion property.
	 *
	 * @param value allowed object is {@link BigDecimal }
	 *
	 */
	public void setSchemaVersion(BigDecimal value) {
		this.schemaVersion = value;
	}

	/**
	 * Gets a map that contains attributes that aren't bound to any typed
	 * property on this class.
	 *
	 * <p>
	 * the map is keyed by the name of the attribute and the value is the string
	 * value of the attribute.
	 *
	 * the map returned by this method is live, and you can add new attribute by
	 * updating the map directly. Because of this design, there's no setter.
	 *
	 *
	 * @return always non-null
	 */
	public Map<QName, String> getOtherAttributes() {
		return otherAttributes;
	}

}
