//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//
package gerbera.fdsnws.datamodel;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;

/**
 * Sensitivity and frequency ranges. The FrequencyRangeGroup is an optional
 * construct that defines a pass band in Hertz (FrequencyStart and FrequencyEnd)
 * in which the SensitivityValue is valid within the number of decibels
 * specified in FrequencyDBVariation.
 *
 * <p>
 * Java class for SensitivityType complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType name="SensitivityType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.fdsn.org/xml/station/1}GainType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="InputUnits" type="{http://www.fdsn.org/xml/station/1}UnitsType"/&gt;
 *         &lt;element name="OutputUnits" type="{http://www.fdsn.org/xml/station/1}UnitsType"/&gt;
 *         &lt;group ref="{http://www.fdsn.org/xml/station/1}FrequencyRangeGroup" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SensitivityType", propOrder = {
	"inputUnits",
	"outputUnits",
	"frequencyStart",
	"frequencyEnd",
	"frequencyDBVariation"
})
public class SensitivityType
		extends GainType {

	@XmlElement(name = "InputUnits", required = true)
	protected UnitsType inputUnits;
	@XmlElement(name = "OutputUnits", required = true)
	protected UnitsType outputUnits;
	@XmlElement(name = "FrequencyStart")
	protected Double frequencyStart;
	@XmlElement(name = "FrequencyEnd")
	protected Double frequencyEnd;
	@XmlElement(name = "FrequencyDBVariation")
	protected Double frequencyDBVariation;

	/**
	 * Gets the value of the inputUnits property.
	 *
	 * @return possible object is {@link UnitsType }
	 *
	 */
	public UnitsType getInputUnits() {
		return inputUnits;
	}

	/**
	 * Sets the value of the inputUnits property.
	 *
	 * @param value allowed object is {@link UnitsType }
	 *
	 */
	public void setInputUnits(UnitsType value) {
		this.inputUnits = value;
	}

	/**
	 * Gets the value of the outputUnits property.
	 *
	 * @return possible object is {@link UnitsType }
	 *
	 */
	public UnitsType getOutputUnits() {
		return outputUnits;
	}

	/**
	 * Sets the value of the outputUnits property.
	 *
	 * @param value allowed object is {@link UnitsType }
	 *
	 */
	public void setOutputUnits(UnitsType value) {
		this.outputUnits = value;
	}

	/**
	 * Gets the value of the frequencyStart property.
	 *
	 * @return possible object is {@link Double }
	 *
	 */
	public Double getFrequencyStart() {
		return frequencyStart;
	}

	/**
	 * Sets the value of the frequencyStart property.
	 *
	 * @param value allowed object is {@link Double }
	 *
	 */
	public void setFrequencyStart(Double value) {
		this.frequencyStart = value;
	}

	/**
	 * Gets the value of the frequencyEnd property.
	 *
	 * @return possible object is {@link Double }
	 *
	 */
	public Double getFrequencyEnd() {
		return frequencyEnd;
	}

	/**
	 * Sets the value of the frequencyEnd property.
	 *
	 * @param value allowed object is {@link Double }
	 *
	 */
	public void setFrequencyEnd(Double value) {
		this.frequencyEnd = value;
	}

	/**
	 * Gets the value of the frequencyDBVariation property.
	 *
	 * @return possible object is {@link Double }
	 *
	 */
	public Double getFrequencyDBVariation() {
		return frequencyDBVariation;
	}

	/**
	 * Sets the value of the frequencyDBVariation property.
	 *
	 * @param value allowed object is {@link Double }
	 *
	 */
	public void setFrequencyDBVariation(Double value) {
		this.frequencyDBVariation = value;
	}

}
