//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//
package gerbera.fdsnws.datamodel;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAnyAttribute;
import jakarta.xml.bind.annotation.XmlAnyElement;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.xml.namespace.QName;

import org.w3c.dom.Element;

/**
 * Description of a site location using name and optional geopolitical
 * boundaries (country, city, etc.).
 *
 * <p>
 * Java class for SiteType complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType name="SiteType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Town" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="County" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Region" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Country" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;any processContents='lax' namespace='##other' maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;anyAttribute processContents='lax' namespace='##other'/&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SiteType", propOrder = {
	"name",
	"description",
	"town",
	"county",
	"region",
	"country",
	"any"
})
public class SiteType {

	@XmlElement(name = "Name", required = true)
	protected String name;
	@XmlElement(name = "Description")
	protected String description;
	@XmlElement(name = "Town")
	protected String town;
	@XmlElement(name = "County")
	protected String county;
	@XmlElement(name = "Region")
	protected String region;
	@XmlElement(name = "Country")
	protected String country;
	@XmlAnyElement(lax = true)
	protected List<Object> any;
	@XmlAnyAttribute
	private Map<QName, String> otherAttributes = new HashMap<QName, String>();

	/**
	 * Gets the value of the name property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getName() {
		return name;
	}

	/**
	 * Sets the value of the name property.
	 *
	 * @param value allowed object is {@link String }
	 *
	 */
	public void setName(String value) {
		this.name = value;
	}

	/**
	 * Gets the value of the description property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * Sets the value of the description property.
	 *
	 * @param value allowed object is {@link String }
	 *
	 */
	public void setDescription(String value) {
		this.description = value;
	}

	/**
	 * Gets the value of the town property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getTown() {
		return town;
	}

	/**
	 * Sets the value of the town property.
	 *
	 * @param value allowed object is {@link String }
	 *
	 */
	public void setTown(String value) {
		this.town = value;
	}

	/**
	 * Gets the value of the county property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getCounty() {
		return county;
	}

	/**
	 * Sets the value of the county property.
	 *
	 * @param value allowed object is {@link String }
	 *
	 */
	public void setCounty(String value) {
		this.county = value;
	}

	/**
	 * Gets the value of the region property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getRegion() {
		return region;
	}

	/**
	 * Sets the value of the region property.
	 *
	 * @param value allowed object is {@link String }
	 *
	 */
	public void setRegion(String value) {
		this.region = value;
	}

	/**
	 * Gets the value of the country property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getCountry() {
		return country;
	}

	/**
	 * Sets the value of the country property.
	 *
	 * @param value allowed object is {@link String }
	 *
	 */
	public void setCountry(String value) {
		this.country = value;
	}

	/**
	 * Gets the value of the any property.
	 *
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the any property.
	 *
	 * <p>
	 * For example, to add a new item, do as follows:
	 * <pre>
	 *    getAny().add(newItem);
	 * </pre>
	 *
	 *
	 * <p>
	 * Objects of the following type(s) are allowed in the list null	null	null	 {@link Element }
     * {@link Object }
	 *
	 *
	 */
	public List<Object> getAny() {
		if (any == null) {
			any = new ArrayList<Object>();
		}
		return this.any;
	}

	/**
	 * Gets a map that contains attributes that aren't bound to any typed
	 * property on this class.
	 *
	 * <p>
	 * the map is keyed by the name of the attribute and the value is the string
	 * value of the attribute.
	 *
	 * the map returned by this method is live, and you can add new attribute by
	 * updating the map directly. Because of this design, there's no setter.
	 *
	 *
	 * @return always non-null
	 */
	public Map<QName, String> getOtherAttributes() {
		return otherAttributes;
	}

}
